name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build image
        run: docker build -t dimberman/foo:bar .
      - name: save image
        run: docker save -o ./image dimberman/foo:bar
  pull-image:
    runs-on: ubuntu-latest
    steps:
      - name: load image
        run: docker load -i ./image
      - name: run image
        run: docker run dimberman/foo:bar

  create-kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.3.0
    - name: Test cluster running
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
    - name: download helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
    - name: create namespace
      run: kubectl create namespace airflow
    - name: pull astronomer helm chart
      run: |
        helm repo add astronomer https://helm.astronomer.io
        helm install airflow --namespace airflow astronomer/airflow
        kubectl get pods --namespace airflow